import { Link } from "react-router-dom";
import Footer from "@/components/Footer";
import Logo from "@/components/Logo";

type Section = { heading: string; body: React.ReactNode };

const PageShell = ({ title, intro, sections }: { title: string; intro: string; sections: Section[] }) => (
  <div className="min-h-screen bg-near-black text-white flex flex-col">
    <header className="border-b border-white/10">
      <div className="container mx-auto py-5 flex items-center justify-between">
        <Logo />
        <Link to="/" className="text-sm text-white/70 hover:text-cyan-accent">← Back to home</Link>
      </div>
    </header>
    <main className="flex-1 py-20">
      <div className="container mx-auto max-w-3xl">
        <h1 className="font-serif text-5xl mb-6">{title}</h1>
        <p className="text-white/75 mb-12 text-lg leading-relaxed">{intro}</p>
        <div className="space-y-10">
          {sections.map((s) => (
            <section key={s.heading}>
              <h2 className="font-serif text-2xl text-cyan-accent mb-3">{s.heading}</h2>
              <div className="text-white/80 leading-relaxed text-justify">{s.body}</div>
            </section>
          ))}
        </div>
      </div>
    </main>
    <Footer />
  </div>
);

export const Disclaimer = () => (
  <PageShell
    title="Disclaimer"
    intro="Please read this disclaimer carefully before using the Kardiosense platform or any information published on this website."
    sections={[
      { heading: "Decision-Support, Not Diagnosis", body: <p>Kardiosense is a clinical decision-support tool. It is not a diagnostic medical device. All outputs generated by the platform must be reviewed and interpreted by a qualified healthcare professional before any clinical action is taken.</p> },
      { heading: "Not a Substitute for Clinical Judgement", body: <p>Nothing on this website or within the Kardiosense application substitutes for the judgement of a licensed clinician, nor for emergency medical care.</p> },
      { heading: "Cardiac Emergencies", body: <p>If you or someone near you is experiencing chest pain, shortness of breath or any other symptom that may indicate a cardiac emergency, contact your local emergency services immediately.</p> },
      { heading: "Regulatory Status", body: <p>Kardiosense is currently pre-commercial. It has not yet been cleared, approved or certified by the U.S. Food and Drug Administration (FDA), the European CE Mark process, or any other regulatory authority.</p> },
    ]}
  />
);

export const Privacy = () => (
  <PageShell
    title="Privacy Policy"
    intro="Your privacy is fundamental to our mission. This policy explains what we collect on this website and how we handle it."
    sections={[
      { heading: "What We Collect", body: <p>Through the waitlist form on this website we collect your name, email address, role, country and any optional message you choose to share. We do not collect any health data on this website.</p> },
      { heading: "How We Store It", body: <p>Your information is stored securely using industry-standard practices and is never sold to third parties.</p> },
      { heading: "Your Rights", body: <p>You may request access to, correction of, or deletion of your data at any time by contacting us. Requests are honoured promptly.</p> },
      { heading: "Compliance", body: <p>Our practices are designed to comply with the EU General Data Protection Regulation (GDPR) and the Uganda Data Protection and Privacy Act 2019.</p> },
    ]}
  />
);

export const Terms = () => (
  <PageShell
    title="Terms and Conditions"
    intro="By accessing this website you agree to the following terms."
    sections={[
      { heading: "Informational Use", body: <p>This website is provided for informational purposes only. No clinical, medical or professional relationship is created by your use of it.</p> },
      { heading: "Updates", body: <p>Kardiosense reserves the right to update, change or remove any content on this website at any time, without prior notice.</p> },
      { heading: "Intellectual Property", body: <p>All content, branding, software, designs and intellectual property on this website are the exclusive property of Kardiosense.</p> },
      { heading: "Governing Law", body: <p>These terms are governed by and construed in accordance with the laws of the Republic of Uganda.</p> },
    ]}
  />
);
